# Generated by Django 4.0.3 on 2022-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
