# Generated by Django 4.0.3 on 2022-03-06 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_image_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='posted_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 6, 6, 53, 47, 440429), null=True),
        ),
    ]
