# Generated by Django 4.0.3 on 2022-03-06 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_alter_image_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='posted_on',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 6), null=True),
        ),
    ]
