# Generated by Django 4.0.3 on 2022-03-06 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_alter_image_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='posted_on',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
