# Generated by Django 4.0.3 on 2022-03-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_alter_image_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='posted_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
